### ISSUE TITLE
Black shark 3 DCS export script

### ISSUE THREAD

**Issue by raidsec** [enertial/streamdeck-dcs-interface#114]
Hello,

would it be possible to integrate a export script for the black shark3?

Regards
raid

**Comment by Mr-7** [comment]
You can copy the black shark 2 one and rename it and it should work. -- Dr Miles G TawellOn 19 Jan 2023, at 20:25, raidsec ***@***.***> wrote:﻿
Hello,
would it be possible to integrate a export script for the black shark3?
Regards
raid

**Comment by raidsec** [comment]
Haha, you are right. Just copy the Ka-50.lua to Ka-50_3.lua and it works. 
Sometimes its so easy. 
Thank you
